baseURL = "https://alchemistsimulator.github.io/"
canonifyURLs = true
languageCode = "en"
defaultContentLanguage = "en"
timeout = "5m"

title = "The Alchemist Simulator"
theme = "hugo-theme-relearn"
relativeURLs = true

[params]
  editURL = "https://github.com/AlchemistSimulator/Alchemist/edit/master/site/content/"
  author.name = "Danilo Pianini"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  mermaid = true
  titleSeparator = "::"
  themeVariant = "relearn"
  disableSeoHiddenPages = true
  disableLanguageSwitchingButton = true
  version = "!development preview!"

[outputs]
  home = ['html', 'rss', 'search']

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
  [markup.highlight]
    style = "base16-snazzy" # choose a color theme or create your own
    guessSyntax = false     # if set to true, avoid unstyled code if no language was given but mermaid code fences will not work anymore

[markup.goldmark.renderer]
  unsafe= true

[languages.en.params]
  landingPageURL = "/"
  landingPageName = "<i class='fas fa-home'></i> Home"

[Languages]
  [Languages.en]
    title = "Documentation for the Alchemist Simulator"
    weight = 1
    languageName = "English"


  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/AlchemistSimulator/Alchemist"
    weight = 10

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-youtube'></i> YouTube channel"
    url = "https://youtube.com/@alchemistsimulator"
    weight = 20

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-camera'></i> Use cases"
    url = "/showcase/"
    weight = 30

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-tags'></i> Tags"
    url = "/tags/"
    weight = 40

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-balance-scale'></i> License"
    url = "/license/"
    weight = 40
